### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by Sha1fei** [alextsk/conway-game-of-life#1]
В большинстве проектов у нас используется typescript, прикрути его к игре плиз.

**Comment by Sha1fei** [comment]
Typescript очень удобен для использования классов, в рамках задания его использование не является обязательным, но у нас все стажеры им пользовались когда переписывали на классах. В целом это остается на твое усмотрение, можно и js оставить, но в игре необходимо использовать классы.

**Comment by Sha1fei** [comment]
Сергей написал, что возникла проблема с typescript а в чем именно она заключается?

**Comment by alextsk** [comment]
хм, даже не знаю, много их. я просто в рамках отчетов писал что разбираюсь с ним, читаю доки, что-то получается, что-то пока нет. сейчас тесты не получается запустить, но я еще не вникал особо
