### ISSUE TITLE
Замечания по view

### ISSUE THREAD

**Issue by chmnkh** [alextsk/conway-game-of-life#12]
View.ts:
- все затипизировать, модификаторы доступа свойств/методов явно написать. Тут как раз яркий пример, когда без типов и модификаторов доступа, глядя на свойства класса, ничего не понятно) причем у тебя там еще и то, что должно бы было быть методами, объявлено как свойства, короче здесь прям порядок надо навести;
- конструктор очень толстый: с addObserver можно сделать то же, что и в модели. Получение кучи ссылок на DOM-элементы я бы тоже вынес, лучше бы читалось;
- именование обработчиков событий: https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_8av0m/ сделай имена как тут указано в 3 пункте (да, у нас пока не реакт, но лучше сразу приучаться к такой схеме, и читать вьюху намного легче станет, когда такой порядок будет);
- избавиться от ручного bind; чтобы не биндить что-то руками, можешь посмотреть в сторону либы decko, или в сторону плагина для бабеля (тут загуглить можно);

Вьюха из всего кода самой сложной на данный момент оказалась, так что после этих исправлений буду еще ее смотреть.

**Comment by alextsk** [comment]
> что должно бы было быть методами, объявлено как свойства

чтобы

> избавиться от ручного bind

поправлю, а почему именно decko или бабель, typescript же поддерживает свои декораторы?

по именованию обработчиков: есть ли смысл в on[ElementName]EventName когда ElementName приходит из конфига? 
можно сделать computed property, думаешь on[this.config.controls.components.play.selector]ClickHandler лучше читается?

**Comment by chmnkh** [comment]
> поправлю, а почему именно decko или бабель, typescript же поддерживает свои декораторы?

это я из личного опыта предложил (то, что лично я использовал), если ты можешь по-другому делать - сделай, а там посмотрим)

> по именованию обработчиков: есть ли смысл в on[ElementName]EventName когда ElementName приходит из конфига?

Ну в ElementName речь не именно о селекторе. Естественно, если у тебя блок "слайдер", то у него скорее всего CSS-класс будет "slider", а компонента будет Slider называться, но тут имеется в виду не CSS-класс конкретный, а просто "название" элемента. Т.е. для блока 'slider' обработчики будут называться handleSlider... не потому, что у него CSS-класс 'slider' (вообще было бы странно, если бы мы здесь на CSS-классы завязывались), а потому что HTML-элементу, на который вешается обработчик, соответствует слайдер.
Точно так же у тебя есть playButton - нам неважно какой там CSS-класс, а важно то, что у нас есть метод handlePlayButtonClick, например, видя который мы сразу понимаем, что он вешается на событие клик для ноды, которая содержит плэй-баттон, а когда называем, не тратим время на придумывание имени.

**Comment by chmnkh** [comment]
т.е. тут оперировать понятиями предметной области надо, а не конкретными CSS-классами.

**Comment by alextsk** [comment]
понял. в ризоме нашел еще вот такой пункт
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_795g0/
они не противоречат друг другу?

**Comment by chmnkh** [comment]
да, не досмотрели, правила в разное время писались разными людьми, мы обсудим, какое правило оставить/изменить а какое убрать, твоего задания это в любом случае не коснется, так что как переделал пусть так и будет
