### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by chmnkh** [alextsk/conway-game-of-life#17]
IState, ILogic, ITemplate:
- убрать неиспользуемый импорт (заметь, это замечание уже было, ну только без темплейт файла)

State.ts
- есть неиспользуемое свойство класса

Model.ts:
- подвинь весь код на строчку вверх, чтобы пустоты сверху не было, раз уж мы здесь

Template.ts
- типизация, модификаторы доступа
- сокращения типа 'sel' не надо юзать, они неочевидные и не нужные вообще
- неиспользуемые переменные убрать
- message, button, и так далее - плохие имена методов
- писать пустой конструктор, чтобы приватное свойство объявить - не надо, можно его проще объявить

Config.ts:
- типизация

View.ts
- типизация всех методов класса как минимум
- конкатенацию строк не использовать
- для обзерверов коллбэки так же вынести методы, как в модели
- в таких вот случаях (см. код ниже), а так же в случаях, где у тебя в рамках одной функции по 50 раз приходится this.config писать, деструктурировать надо, а не так писать:
```
const components = this.config.controls.components;
```
у тебя много раз такие штуки во вьюхе, деструктуризация везде и всюду юзается, так что будет полезным сразу с ней писать.
- сокращение 'sel' - то же замечание, что и в темплейте

Общие:
- // tslint:disable-line - не надо везде вставлять активно. Везде где у тебя сейчас задизейблен линтер так, можно это убрать и отформатировать адекватно. Вообще это, на мой взгляд, из разряда "забивать на типизацию, когда что-то не билдится, а с типами разобраться проблемно, и писать any", потому что линтер не просто так же используется, и при возникновении каких-то проблем его тупо дизейблить - плохая привычка. Есть конечно исключительные случаи везде, но у тебя это не так.
- проблемы, из-за которых проект не билдится,  я не указывал

**Comment by alextsk** [comment]
> деструктурировать надо, а не так писать
const components = this.config.controls.components

потому что 
const { config: { controls: { components } } } = this;
гораздо понятнее?

> писать пустой конструктор, чтобы приватное свойство объявить

не только объявить, в основном чтобы передать в конструктор при вызове

> проблемы, из-за которых проект не билдится, я не указывал

тут непонятно, они есть но ты их не указывал? у меня все билдится норм, напиши плиз если у тебя нет

**Comment by chmnkh** [comment]
> потому что
const { config: { controls: { components } } } = this;
гораздо понятнее?

ну во-первых либо так: 
```const { components }  = this.config.controls``` (уже меньше букв стало), это если this.config один раз используется. Либо, если this.config используется несколько раз, то ```const { controls: { components }, ...еще что-то  } = this.config```.
во-вторых, когда у тебя с конфига куча всякого разного достается, то лучше один раз написать деструктуризацию, чем потом везде писать this.config...

> не только объявить, в основном чтобы передать в конструктор при вызове

здесь я ошибся, да

> тут непонятно, они есть но ты их не указывал? у меня все билдится норм, напиши плиз если у тебя нет

у меня не билдится (npm run serve) , но у Валентина билдится, например. Но ворнинги у Валентина при сборке те же самые, и их в любом случае убрать надо, поэтому пока копать в сторону того, почему именно у меня не билдится, не будем сейчас. Посмотри в консоли ворнинги при сборке, и их убери, а там глянем, соберется у меня или нет)
