### ISSUE TITLE
Замечания по модели

### ISSUE THREAD

**Issue by chmnkh** [alextsk/conway-game-of-life#8]
IState, ILogic:
- убрать неиспользуемый импорт;

Logic:
- в getCellState в последних двух строчках избыточная логика (проверяется одно и то же условие и один и тот же результат в else ветке тернарника)

завтра буду сюда дополнять.

**Comment by chmnkh** [comment]
продолжение:
Logic:
- updateGrid:
```
        const isAlive = this.getCellState(grid, x + 1, y + 1) === 1;
        if (isAlive) {
          return (neigboursCount > 3) || (neigboursCount < 2) ? 0 : 1;
        }
        return (neigboursCount === 3) ? 1 : 0;
```
тут все литералы в константы повыносить (опять же, танцы с индексами, где + 1 -1 можно оставлять) и использовать текущий enum (0 и 1 это видимо он).

State:
- куча методов неиспользуемых, их убрать;
- setGrid: флаг забыл убрать;
- diff: циклы for переписать на методы массивов;
- setWidth: newWidth: number зачем-то кастится в number), newrow => newRow;
- setHeight: с newHeight то же самое, что и с newWidth;
- есть какая-то причина, по которой ты из методов какое-то значение возвращаешь, хотя оно тебе по сути-то не нужно потом нигде, где эти методы используются? setGrid и updateHistory, например, возвращают что-то, но это потом нигде не используется, почему они тогда вообще что-то возвращают? Эти ретёрны лишние, которые никакого смысла не имеют, чтение и понимание кода в целом усложняют, на мой взгляд.

Model: 
- console.log забыл убрать;
- чтобы все было еще лаконичнее, круто будет все коллбэки, передающиеся в addObserver вынести в свои методы модели, и вызовы addObserver тоже в свой отдельный метод, который будет в конструкторе вызываться.

Общие замечания:
- типизация. Во многих методах параметры не типизированы, а потому они как any воспринимаются, что чревато может быть. Надо затипизировать.

**Comment by alextsk** [comment]
> зачем-то кастится в number

 значение инпута приходит строкой, где-то его нужно кастить в число, почему не здесь?

>  вызовы addObserver тоже в свой отдельный метод

что-то вроде this.init()?

>  все литералы в константы повыносить 

2 и 3 можно оставить?

**Comment by chmnkh** [comment]
> значение инпута приходит строкой, где-то его нужно кастить в число, почему не здесь?

Потому что модель ни про какой инпут знать не знает, и в методе она принимает number.

> что-то вроде this.init()?

initObservers имхо лучше подойдет

> 2 и 3 можно оставить?

на самом деле на твое усмотрение здесь, можно и оставить
